// *****************************************************************************
// * Copyright (c) 2020, 2021, 2022 joshua.tee@gmail.com. All rights reserved.
// *
// * Refer to the COPYING file of the official project for license.
// *****************************************************************************

#include "UtilityModelSpcHrefInterface.h"

const vector<string> UtilityModelSpcHrefInterface::sectorsLong{
    "CONUS",
    "Central Plains",
    "Mid Atlantic",
    "Midwest",
    "Northeast",
    "Northern Plains",
    "Northwest",
    "Southeast",
    "Southern Plains",
    "Southwest"
};

const vector<string> UtilityModelSpcHrefInterface::sectors{
    "conus",
    "cp",
    "ma",
    "mw",
    "ne",
    "np",
    "nw",
    "se",
    "sp",
    "sw"
};

const vector<string> UtilityModelSpcHrefInterface::params{
    "guidance_hail_spchazcal_004h",
    "guidance_tor_spchazcal_004h",
    "guidance_wind_spchazcal_004h",
    "guidance_hail_spchazcal_024h",
    "guidance_tor_spchazcal_024h",
    "guidance_wind_spchazcal_024h",
    "guidance_hrefct_004h",

    "500w_mean,500h_mean",
    "700w_mean,700h_mean",
    "850w_mean,850h_mean",
    "sfct_mean,10mwind_mean,mslp_mean",
    "sfctd_mean,10mwind_mean,mslp_mean",
    "cloudcover_low_mean,cloudcover_mid_mean,cloudcover_high_mean",
    "pwat_mean",
    "pwat_prob050080",

    "sbcape_max,sfc500shear_mean",
    "sbcape_mean,sfc500shear_mean",
    "sbcape_prob0500",
    "sbcape_prob1000",
    "sbcape_prob2000",
    "sbcape_ps",
    "mucape_mean,sfc500shear_mean",
    "srh03_mean",
    "srh01_mean",
    "stpfixed_mean",
    "stpfixed_prob01",
    "stpfixed_prob03",

    "qpf_001h_mean_ptype",
    "snowfall_001h_mean",
    "snowfall_001h_prob01",
    "snowfall_001h_prob02",
    "snowfall_012h_max",
    "snowfall_012h_mean",
    "snowfall_012h_pmm",
    "snowfall_012h_prob04",
    "snowfall_012h_prob08",
    "snowfall_012h_prob12",
    "snowfall_012h_ps",
    "snowfall_024h_max",
    "snowfall_024h_mean",
    "snowfall_024h_pmm",
    "snowfall_024h_prob04",
    "snowfall_024h_prob08",
    "snowfall_024h_prob12",
    "snowfall_024h_ps",
    "viswnd_prob0025035",
    "frzrfram_003h_mean",
    "frzrqpf_003h_max",
    "frzrqpf_003h_mean",
    "frzrqpf_003h_prob006",
    "frzrfram_024h_mean",
    "frzrqpf_024h_max",
    "frzrqpf_024h_mean",

    "fosberg_max",
    "fosberg_mean",
    "fosberg_prob050",
    "fosberg_prob075",
    "10mwindhm_mean_mph_fill,10mwind_mean_mph",
    "10mgust_max_mph_fill,10mwind_mean_mph",
    "sfcrh_mean",
    "rhwnd_prob1030",
    "rhwnd_prob1515",
    "rhwnd_prob1520",
    "rhwnd_prob2015",
    "rhwnd_prob2020",

    "qpf_001h_mean_ptype",
    "qpf_001h_prob01",
    "qpf_003h_nh1",
    "qpf_003h_mean",
    "qpf_003h_pmm",
    "qpf_006h_max",
    "qpf_006h_mean",
    "qpf_006h_pmm",
    "qpf_006h_prob01",
    "qpf_006h_prob02",
    "qpf_006h_prob03",
    "qpf_006h_ps",
    "qpf_012h_max",
    "qpf_012h_mean",
    "qpf_012h_pmm",
    "qpf_012h_ps",

    "cref_members hrwnssl",
    "cref_members hrwarw",
    "cref_members hrwnmmb",
    "cref_members namnest",
    "cref_pb40_members",
    "cref_ps",
    "ref1km_003hmax_nh40",
    "ref1km_003hmax_pb40_members",
    "ref1km_024hmax_nh40",
    "ref1km_024hmax_pb40_members",
    "uh25_003hmax_max",
    "uh25_003hmax_nh075_fill",
    "uh25_003hmax_nh150_fill",
    "uh25_003hmax_pb075_members,uh25_003hmax_nh075",
    "uh25_003hmax_pb150_members,uh25_003hmax_nh150",
    "uh25_024hmax_max,uh25_024hmax_nh075",
    "uh25_024hmax_nh075_fill",
    "uh25_024hmax_nh150_fill",
    "uh25_024hmax_pb075_members,uh25_024hmax_nh075",
    "uh25_024hmax_pb150_members,uh25_024hmax_nh150",
    "wspd_003hmax_max",
    "wspd_003hmax_pb30_members",
    "wspd_024hmax_max",
    "wspd_024hmax_pb30_members"
};

const vector<string> UtilityModelSpcHrefInterface::labels{
    "4-hr HREF/SREF Calibrated: Hail",
    "4-hr HREF/SREF Calibrated: Tornado",
    "4-hr HREF/SREF Calibrated: Wind",
    "24-hr HREF/SREF Calibrated: Hail",
    "24-hr HREF/SREF Calibrated: Tornado",
    "24-hr HREF/SREF Calibrated: Wind",
    "4-hr HREF Calibrated: Thunder",

    "500 mb Height/Wind",
    "700 mb Height/Wind",
    "850 mb Height/Wind",
    "2m AGL Temperature/MSLP/Wind",
    "2m AGL Dew Point/MSLP/Wind",
    "Cloud Cover: mean",
    "Precipitable Water: mean",
    "Precipitable Water: CP{>0.5, <0.8}",

    "Surface Based CAPE: max",
    "Surface Based CAPE: mean",
    "Surface Based CAPE: P{>500}",
    "Surface Based CAPE: P{>1000}",
    "Surface Based CAPE: P{>2000}",
    "Surface Based CAPE: stamps",
    "Most Unstable CAPE: mean",
    "0-3 km SRH: mean",
    "0-1 km SRH: mean",
    "Fixed-Layer STP mean",
    "Fixed-Layer STP P{>1}",
    "Fixed-Layer STP P{>3}",

    "1-hr QPF and Precip Type: mean",
    "1-hr Snowfall: mean",
    "1-hr Snowfall: P{>1\"}",
    "1-hr Snowfall: P{>2\"}",
    "12-hr Snowfall: max",
    "12-hr Snowfall: mean",
    "12-hr Snowfall: PMM",
    "12-hr Snowfall: P{>4\"}",
    "12-hr Snowfall: P{>8\"}",
    "12-hr Snowfall: P{>12\"}",
    "12-hr Snowfall: stamps",
    "24-hr Snowfall: max",
    "24-hr Snowfall: mean",
    "24-hr Snowfall: PMM",
    "24-hr Snowfall: P{>4\"}",
    "24-hr Snowfall: P{>8\"}",
    "24-hr Snowfall: P{>12\"}",
    "24-hr Snowfall: stamps",
    "Blizzard: CP{Vis, 10-m Vh} w/ snow",
    "3-hr Freezing Rain: FRAM mean",
    "3-hr Freezing Rain: QPF max",
    "3-hr Freezing Rain: QPF mean",
    "3-hr Freezing Rain: P{>0.06\"}",
    "24-hr Freezing Rain: FRAM mean",
    "24-hr Freezing Rain: QPF max",
    "24-hr Freezing Rain: QPF mean",

    "Fosberg Index: max",
    "Fosberg Index: mean",
    "Fosberg Index: P{>50}",
    "Fosberg Index: P{>75}",
    "10 m AGL Wind (Hourly Max): mean",
    "10 m AGL Gust: mean",
    "Relative Humidity: mean",
    "Relative Humidity and Wind: CP{RH<10%, V>30mph}",
    "Relative Humidity and Wind: CP{RH<15%, V>15mph}",
    "Relative Humidity and Wind: CP{RH<15%, V>20mph}",
    "Relative Humidity and Wind: CP{RH<20%, V>15mph}",
    "Relative Humidity and Wind: CP{RH<20%, V>20mph}",

    "1-hr QPF and Precip Type: mean",
    "1-hr QPF: P{>1\"}",
    "3-hr QPF: max",
    "3-hr QPF: mean",
    "3-hr QPF: pmm",
    "6-hr QPF: max",
    "6-hr QPF: mean",
    "6-hr QPF: pmm",
    "6-hr QPF: P{>1\"}",
    "6-hr QPF: P{>2\"}",
    "6-hr QPF: P{>3\"}",
    "6-hr QPF: stamps",
    "24-hr QPF: max",
    "24-hr QPF: mean",
    "24-hr QPF: pmm",
    "24-hr QPF: stamps",

    "Reflectivity: hrwnssl",
    "Reflectivity: hrwarw",
    "Reflectivity: hrwnmmb",
    "Reflectivity: namnest",
    "Reflectivity: PB{>40}",
    "Reflectivity: stamps",
    "3-hr max Reflectivity: max",
    "3-hr max Reflectivity: PB{>40}",
    "24-hr max Reflectivity: max",
    "24-hr max Reflectivity: PB{>40}",
    "3-hr max Updraft Helicity (2-5 km): max",
    "3-hr max Updraft Helicity (2-5 km): NP{>75}",
    "3-hr max Updraft Helicity (2-5 km): NP{>150}",
    "3-hr max Updraft Helicity (2-5 km): PB{>75}",
    "3-hr max Updraft Helicity (2-5 km): PB{>150}",
    "24-hr max Updraft Helicity (2-5 km): max",
    "24-hr max Updraft Helicity (2-5 km): NP{>75}",
    "24-hr max Updraft Helicity (2-5 km): NP{>150}",
    "24-hr max Updraft Helicity (2-5 km): PB{>75}",
    "24-hr max Updraft Helicity (2-5 km): PB{>150}",
    "3-hr max Updraft: max",
    "3-hr max Updraft: PB{>20}",
    "24-hr max Updraft: max",
    "24-hr max Updraft: PB{>20}",
    "3-hr max Wind Speed: max",
    "3-hr max Wind Speed: PB{>30}",
    "24-hr max Wind Speed: max",
    "24-hr max Wind Speed: PB{>30}",
    "10m 3-hr max Wind Speed: max PB{>30}",
    "10m 3-hr max Wind Speed: PB{>30}",
    "10m 24-hr max Wind Speed: max",
    "10m 24-hr max Wind Speed: PB{>30}"
};
